### PR TITLE
Signature of periphery bus has changed. 

### PR DESCRIPTION
**Pull request by chick**
Add name "periphery_bus"
This must be merged before PR #202 to avoid a failing test

### CODE REVIEW

**Comment by ucbjrl** [comment]
Pr #185 attempted to do this, and is still waiting for review.

**Comment by chick** [comment]
I'll defer to the far more imaginatively named PR #185 
You are always a step ahead of me.

**Comment by ucbjrl** [comment]
Let's accept this PR. It passed tests whereas #185 didn't.

**Comment by chick** [comment]
Ok with me. Do you want to review?

**Pull request merged**
