### PR TITLE
Add Stochastic Rounding

### PR DESCRIPTION
**Pull request by tampler**
Add Stochastic Rounding

### CODE REVIEW

**Comment by grebe** [comment]
FYI, it looks like you're starting from a release candidate (and merging master in). Perhaps @ucbjrl has different ideas (he manages releases), but I think it's better to start directly from master so you don't have to deal with merging the irrelevant `build.sbt` changes.

If you want to work off a release to make it easier to build stuff, it might be easier to work off the release locally and rebase all your changes when you're ready to push.

**Comment by ucbjrl** [comment]
Right. All development work should be done in master (or a branch checked out from master). I can understand wanting to use a release branch in order to test against the released versions of chisel and firrtl (and not have to publish them locally).

To test against the released versions of chisel and firrtl, you can copy the `defaultVersions` map from the most recent release version, or better yet, set the appropriate environment/shell variables to specify the released versions of chisel and firrtl you wish to test against.

**Comment by tampler** [comment]
I can't work with your master, since I get unresolved dependencies. I'm working with a v1.1.3 tag. What should I do ?

**Comment by grebe** [comment]
There are a couple options, perhaps the simplest is to do work with [dsp-framework](https://github.com/ucb-art/dsp-framework/tree/diplomacyPort), a repository that tracks dependencies and has a makefile for building the dependencies in the right order. The link here points at the diplomacyPort branch which references more modern versions of the dependencies. dsptools is included in dsp-framework.

What I usually do in practice is clone all the chisel dependencies (firrtl, firrtl-interpreter, treadle, chisel3, chisel-testers) and run

```
sbt publishLocal
```

for each one. This compiles the project and publishes a jar and pom in ~/.ivy2/local where other instances of sbt can find them. It's a pain to do the first time, but is usually not something you have to do too often.

If all of these seems overly complicated, I think you can probably do you work based off the release branch, rebase on master, and push. Travis will check that tests still pass, so it's not the end of the world for your dev work to be on a different branch than what you actually push.

**Comment by tampler** [comment]
Paul, can we make this simpler ? You make a clean checkout, put all dependencies into a local folder, update sbt appropriately and simply upload a tar-ed project to some shared place. I'll do my job and toss it back to you to integrate changes.

**Comment by grebe** [comment]
I sent you a bzip with my prebuilt dependencies.

**Comment by tampler** [comment]
Paul, could you pls help me with this PR ? I created this for v1.1.3, but now working in Master. Should I close this and open a new one? I can't follow changes being shown here, that's not my work :)

I also tried to create own branch for my current work, but Github says that I can't push it since I have no permissions to the usb-bar/dsptools.git

**Comment by tampler** [comment]
Discarded PR due to version inconsistency

**Pull request closed without merging**
