### PR TITLE
TypeclassSpec tests were failing quietly

### PR DESCRIPTION
**Pull request by grebe**
Integer[T] and Signed[T] are failing for me

### CODE REVIEW

**Comment by shunshou** [comment]
I'll take a look. Would be useful to still add in your Lit checks tho!

**Comment by shunshou** [comment]
Talked to Paul. The tests that were failing were wrong to begin with. Need less copy pasta.

**Comment by shunshou** [comment]
Still plz add in Lit check. Remove the failing tests or correct them. And fine, go ahead and add ConvertableTo with DspComplex. I still disagree that you should have Double -> DspComplex (with only Real nonzero) in favor of more explicit adds, subtracts, and multiplies with real/imag #'s but w/e. As long as it's cleanly integrated...

**Comment by shunshou** [comment]
^ Unless these tests were updated, this shouldn't be merged. The tests themselves were wrong.

**Comment by grebe** [comment]
Yeah, don't merge. I'll get to it eventually...

**Pull request merged**
